INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('pop')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('rock')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('classic')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('alternative')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('metal')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('techno')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('electronic')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('disco')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('dance')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('dreamy')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')
INSERT INTO `gatunki_enum`(`nazwa`) VALUES ('')

INSERT INTO `artysta`(`imie`, `nazwisko`, `pochodzenie`, `wiek`, `plec`, `opis`, `artysta_zespol_FK`, `artysta_plyta_FK`, `artysta_kolaboracja_FK`)
VALUES ('Billy','Armstrong','Oakland','45','mężczyzna','amerykański muzyk, kompozytor, wokalista i autor tekstów. Billie Joe Armstrong znany jest przede wszystkim z wieloletnich występów w zespole rockowym Green Day. Występuje ponadto w zespołach Foxboro Hot Tubs i Pinhead Gunpowder. W latach 2003-2005 występował także w grupie The Network.','1','2','3')